# fly.toml app configuration file generated for beef-solitary-dream-5712 on 2024-12-16T10:36:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beef-solitary-dream-5712'
primary_region = 'otp'

[build]
  dockerfile = "Dockerfile"
[build.args]
  COMPOSE_FILE="docker-compose/docker-compose-dev.yaml"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
source = "postgres_data"
destination = "/var/lib/postgresql/data"

[[mounts]]
source = "scylla_data"
destination = "/var/lib/scylla"